In [1]:
############################# 
## Homework Assignment Two ##
##     Mollie A. Pepper    ##
## Due 04/19/2022 11:59 PM ##
#############################

In [2]:
# import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.compose import make_column_selector as col_selector

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline, Pipeline

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB



# import data set
data = pd.read_csv('adult_income.csv')

In [3]:
# one
print(data.columns)

#two
rowcol = data.shape
print(rowcol)
print("This data frame has", rowcol[1], "columns and", rowcol[0], "rows!")

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'gender',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')
(8739, 15)
This data frame has 15 columns and 8739 rows!


In [4]:
# three

#print number of missings per var
print(data.isnull().sum())

# CHECK FOR ?s
#print(data["age"].value_counts())
print(data["workclass"].value_counts())
#print(data["fnlwgt"].value_counts())
#print(data["education"].value_counts())
#print(data["education.num"].value_counts())
#print(data["marital.status"].value_counts())
print(data["occupation"].value_counts())
#print(data["relationship"].value_counts())
#print(data["race"].value_counts())
#print(data["gender"].value_counts())
#print(data["capital.gain"].value_counts())
#print(data["capital.loss"].value_counts())
#print(data["hours.per.week"].value_counts())
print(data["native.country"].value_counts())
#print(data["income"].value_counts())



"""
the following vars have ?s
workclass
occupation
native country

"""

# replace ?s
data["workclass"] = data["workclass"].str.replace("?", "Other")
data["occupation"] = data["occupation"].str.replace("?", "Other")
data["native.country"] = data["native.country"].str.replace("?", "Other")


age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
gender            0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64
Private             5833
Self-emp-not-inc     753
Local-gov            615
?                    490
Self-emp-inc         414
State-gov            348
Federal-gov          283
Without-pay            3
Name: workclass, dtype: int64
Prof-specialty       1360
Exec-managerial      1345
Craft-repair         1068
Sales                1046
Adm-clerical          906
Other-service         660
?                     490
Machine-op-inspct     487
Transport-moving      412
Handlers-cleaners     281
Tech-support          253
Farming-fishing       235
Protective-serv       165
Priv-house-serv        28
Armed-Forces            3
Name: occupation, dtype: int64
United-States                 7875
?

C:\Users\l1map01\AppData\Local\Temp\ipykernel_27168\502833839.py:34: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["workclass"] = data["workclass"].str.replace("?", "Other")
C:\Users\l1map01\AppData\Local\Temp\ipykernel_27168\502833839.py:35: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["occupation"] = data["occupation"].str.replace("?", "Other")
C:\Users\l1map01\AppData\Local\Temp\ipykernel_27168\502833839.py:36: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["native.country"] = data["native.country"].str

In [5]:
# four

data_y = data["income"]
data = data.drop(["income"], axis=1)
data_1 = data.copy(deep=True)

print(data.dtypes)
#print(data.head)


# select categorical data
categorical_cols_obj = col_selector(dtype_include=object)
print(type(categorical_cols_obj))
categorical_features = categorical_cols_obj(data)
# select numeric data
int_cols_obj = col_selector(dtype_include="int64")
numeric_features = int_cols_obj(data)

#transform and combine
df_cat = data[categorical_features]
ob_encoded = preprocessing.OrdinalEncoder()
cat_encoded = ob_encoded.fit_transform(df_cat)
print(cat_encoded)


X = np.hstack([cat_encoded, np.array(data[numeric_features])])

#print(x.shape)




age                int64
workclass         object
fnlwgt             int64
education         object
education.num      int64
marital.status    object
occupation        object
relationship      object
race              object
gender            object
capital.gain       int64
capital.loss       int64
hours.per.week     int64
native.country    object
dtype: object
<class 'sklearn.compose._column_transformer.make_column_selector'>
[[ 2. 11.  6. ...  4.  0. 39.]
 [ 3. 11.  6. ...  4.  0. 39.]
 [ 2. 15.  6. ...  2.  0. 39.]
 ...
 [ 2.  9.  6. ...  0.  0. 39.]
 [ 3.  8.  2. ...  4.  1. 39.]
 [ 3.  9.  4. ...  4.  1. 39.]]


In [6]:
# five

np.random.seed(0)

x = data

yb = preprocessing.LabelEncoder()
y = yb.fit_transform(data_y)

preprocessor = ColumnTransformer(
               transformers=[
               ('num', StandardScaler(), numeric_features),
               ('cat', OrdinalEncoder(), categorical_features)])

clf = make_pipeline(preprocessor, LogisticRegression(max_iter=500))

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                    random_state=0)

clf.fit(x_train, y_train)
print("model score: %.3f" % clf.score(x_test, y_test))


model score: 0.807


In [10]:
# six
xdr_train, xdr_test, ydr_train, ydr_test = train_test_split(X, y, test_size=0.2, random_state=2)

"""
Decision Tree
"""
dtree = DecisionTreeClassifier()
dtree.fit(xdr_train,ydr_train)   

predict=dtree.predict(xdr_test) # predicted y from the x test                              
predict

print("Decision Tree accuracy is:", accuracy_score(ydr_test, predict)*100)

"""
Random Forest
"""

rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(xdr_train, ydr_train)

rfc_predict = rfc.predict(xdr_test)  
print("Random Forest accuracy is:", accuracy_score(ydr_test,rfc_predict)*100)    

"""
Naive Bayes
"""
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)
gnb = GaussianNB()

gnb.fit(x_train, y_train)

y_pred = gnb.predict(x_test)

print("Naive Bayes accuracy:", metrics.accuracy_score(y_test, y_pred)*100)


Decision Tree accuracy is: 85.1258581235698
Random Forest accuracy is: 87.24256292906179
Naive Bayes accuracy: 80.94965675057209


In [8]:
# seven

"""
The results above show that while all three classifiers are above 80% accuracy,
random forest and decision tree are quite a bit more accurate than the naive bayes method.
Overall, a random forest classifier would be the best choice for this model.
"""

'\nThe results above show that while all three classifiers are above 80% accuracy,\nrandom forest and decision tree are quite a bit more accurate than the naive bayes method.\nOverall, a random forest classifier would be the best choice for this model.\n'

In [9]:
"""
Summary/Conclusion:
In the categorical_cols_conversion file we learned how to transform categorical variables into numeric values so that they can be used in our models. 
There are two main types of encoding that we discussed: ordinal and one-hot. One hot creates one variable for each distinct category, assigning it a value 
of one when the observation has that value and zero otherwise. Ordinal assigns an integer value to each distinct category. 

To do this, one needs to check for missing values in the dataset, and then remove the target variable from the data frame. 
Next, split the remainder of the dataset based on whether the variable is numeric or categorical. 
There are different ways to perform encoding. Firstly, we can create an ordinal encoder object and use fit_transform to create an encoded version of the categorical variables. 
Then the encoded categorical variables can be appended to the numerical variables. This method does not standardize the numeric variables though; one way to resolve this is to 
instead use cat.codes for the categorical subset and standard scaler to standardize the numerical subset. This can all be done in one step by using the ColumnTransformer 
function. We also discussed using pipelines to build models.

"""

'\nSummary/Conclusion:\nIn the categorical_cols_conversion file we learned how to transform categorical variables into numeric values so that they can be used in our models. \nThere are two main types of encoding that we discussed: ordinal and one-hot. One hot creates one variable for each distinct category, assigning it a value \nof one when the observation has that value and zero otherwise. Ordinal assigns an integer value to each distinct category. \n\nTo do this, one needs to check for missing values in the dataset, and then remove the target variable from the data frame. \nNext, split the remainder of the dataset based on whether the variable is numeric or categorical. \nThere are different ways to perform encoding. Firstly, we can create an ordinal encoder object and use fit_transform to create an encoded version of the categorical variables. \nThen the encoded categorical variables can be appended to the numerical variables. This method does not standardize the numeric variables